### ISSUE TITLE
Build Markdown + frontmatter article system

### ISSUE THREAD

**Issue by StanleyMasinde** [StanleyMasinde/Lnky#78]
- [ ] Store articles in `content/articles/slug.md`.
- [ ] Frontmatter format:

```yaml
title:
description:
publishedAt:
tags:
ogImage:
canonical:
```

- Load using Nuxt Content or a file reader.
